# -*- coding: utf-8 -*-
"""MediFlow_Parte1_IA_Multimoda-v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OwrgTUF9cESK68yQ_4mjQRebp7Y_Bqk0

# MediFlow - Parte 1
## IA Multimodal, Agentes & Lógica de Decisión

## INSTALACIONES
"""

# instalaciones

!pip install -q google-genai pydantic

## importaciones y constantes

from google import genai
from google.colab import userdata

API_KEY = userdata.get("GEMINI_API_KEY")

if not API_KEY:
    raise ValueError("No se encontró GEMINI_API_KEY en los secretos de Colab.")

client = genai.Client(api_key=API_KEY)

print("Cliente Gemini configurado correctamente.")

import time

def consultar_gemini(
    prompt,
    archivo=None,
    modelos=None,
    intentos_por_modelo=2
):
    if modelos is None:
        modelos = [
            "gemini-3.8-flash",
            "gemini-3.1-flash-lite",
            "gemini-2.5-flash"
        ]

    # Gemini recibe el archivo y el prompt cuando hay un archivo adjunto
    contents = [archivo, prompt] if archivo else prompt

    for modelo in modelos:
        for intento in range(1, intentos_por_modelo + 1):
            try:
                print(
                    f"Intentando con {modelo} "
                    f"(intento {intento}/{intentos_por_modelo})"
                )

                respuesta = client.models.generate_content(
                    model=modelo,
                    contents=contents
                )

                if respuesta.text:
                    print(f"Respuesta obtenida con {modelo}.")
                    return respuesta.text

                print(f"{modelo} devolvió una respuesta vacía.")

            except Exception as e:
                print(
                    f"Falló {modelo}, intento "
                    f"{intento}/{intentos_por_modelo}: {e}"
                )

                if intento < intentos_por_modelo:
                    espera = 2 * intento
                    print(f"Reintentando en {espera} segundos...")
                    time.sleep(espera)

        print(f"El modelo {modelo} falló. Probando siguiente modelo...")

    raise RuntimeError(
        "No fue posible obtener una respuesta de ninguno de los modelos."
    )

"""## DATOS DE ENTRADA"""

# subida de archivos

from google.colab import files
import time

print("Sube un documento clínico (PDF, PNG, JPG):")
uploaded = files.upload()

if not uploaded:
    raise ValueError("No se subió ningún archivo.")

nombre_archivo = next(iter(uploaded))

# Subir el archivo a Gemini
archivo_gemini = client.files.upload(file=nombre_archivo)

print(f"Archivo {nombre_archivo} subido a Gemini con éxito.")

# Esperar a que Gemini procese el archivo
time.sleep(2)

"""## MODELADO DE DATOS"""

# deficiones de pydantic / modelos de datos

from typing import Optional
from pydantic import BaseModel, Field, field_validator


class Clasificacion(BaseModel):
    tipo_documento: str
    especialidad: str
    nivel_prioridad: str = Field(
        description="Rutina o Urgente"
    )
    score_confianza_clasificacion: float


class Paciente(BaseModel):
    nombre: str
    edad: Optional[int] = None

    @field_validator("edad", mode="before")
    @classmethod
    def convertir_edad(cls, valor):
        if valor is None:
            return None

        if isinstance(valor, int):
            return valor

        if isinstance(valor, str):
            return int(valor.split()[0])

        return valor


class MedicoSolicitante(BaseModel):
    nombre: str
    matricula: Optional[str] = Optional


class DatosExtraidos(BaseModel):
    paciente: Paciente
    medico_solicitante: Optional[MedicoSolicitante] = None
    estudio_realizado: Optional[str] = None
    diagnostico_principal: Optional[str] = None
    cie10_sugerido: Optional[str] = None


class NotificacionGenerada(BaseModel):
    canal: str
    mensaje: str


class DecisionEnrutamiento(BaseModel):
    destino_principal: str
    requiere_auditoria_humana: bool
    justificacion_enrutamiento: str
    notificacion_generada: Optional[NotificacionGenerada] = None


class AlmacenamientoOCI(BaseModel):
    bucket: str
    ruta_objeto: str
    status_backup: str


class RespuestaTriaje(BaseModel):
    status: str
    documento_id: str
    clasificacion: Clasificacion
    datos_extraidos: DatosExtraidos
    decision_enrutamiento: DecisionEnrutamiento
    almacenamiento_oci: AlmacenamientoOCI

class ExtraccionClinica(BaseModel):
    tipo_documento: str | None = None
    canal_origen: str | None = None
    paciente: Paciente
    medico_solicitante: Optional[MedicoSolicitante] = None
    estudio: Optional[str] = None
    indicacion_clinica: Optional[str] = None
    diagnostico_principal: Optional[str] = None
    cie10_sugerido: Optional[str] = None
    nivel_prioridad: Optional[str] = None

"""## EXTRACCIÓN ESTRUCTURADA CON LLM"""

# Prompt para extracción estructurada

prompt_extraccion = """
Eres un agente de triaje clínico.

Analiza el documento clínico adjunto y extrae únicamente la información
que esté explícitamente presente en el documento.

No inventes, completes ni supongas datos que no aparezcan en el documento.

Devuelve ÚNICAMENTE un JSON válido, sin texto adicional ni formato Markdown,
con esta estructura:

{
    "tipo_documento": null,
    "canal_origen": null,
    "paciente": {
        "nombre": null,
        "edad": null
    },
    "medico_solicitante": {
        "nombre": null,
        "matricula": null
    },
    "estudio": null,
    "indicacion_clinica": null,
    "diagnostico_principal": null,
    "cie10_sugerido": null,
    "nivel_prioridad": null
}

Reglas:

- Si un dato no está presente o no puede determinarse con claridad,
  utiliza null.
- "nivel_prioridad" solo puede ser "Rutina" o "Urgente".
- "Urgente" corresponde a una situación que el documento indique
  explícitamente como urgente, crítica o que requiera atención inmediata.
- "Rutina" corresponde a los casos que no presenten una indicación
  explícita de urgencia.
- No utilices "Ambiguo" como nivel de prioridad.
- La ambigüedad, información faltante o baja confianza será evaluada
  posteriormente por el sistema.
- Conserva los datos tal como aparecen en el documento.
- No generes diagnósticos, códigos CIE-10 ni información clínica que
  no esté respaldada por el documento.
"""

"""## Para extraer"""

# Ejecución de la extracción

print("Procesando documento...")

resultado_texto = consultar_gemini(
    prompt=prompt_extraccion,
    archivo=archivo_gemini
)

print("Extracción completada.")

import json

texto_limpio = resultado_texto.strip()

if texto_limpio.startswith("```"):
    lineas = texto_limpio.split("\n")
    texto_limpio = "\n".join(lineas[1:-1])

datos_extraidos = json.loads(texto_limpio)

print(json.dumps(
    datos_extraidos,
    indent=2,
    ensure_ascii=False
))

# Validación de la extracción

extraccion_validada = ExtraccionClinica.model_validate(datos_extraidos)

print("Extracción validada correctamente.")
print(extraccion_validada.model_dump_json(indent=2))

"""## SCORE DE CONFIANZA

#### COMPLETITUD
"""

# Cálculo del score de completitud

def score_completitud(extraccion):
    campos = [
        extraccion.tipo_documento,
        extraccion.canal_origen,
        extraccion.paciente.nombre,
        extraccion.paciente.edad,
        extraccion.medico_solicitante.nombre
            if extraccion.medico_solicitante else None,
        extraccion.medico_solicitante.matricula
            if extraccion.medico_solicitante else None,
        extraccion.estudio,
        extraccion.indicacion_clinica,
        extraccion.diagnostico_principal,
        extraccion.cie10_sugerido,
        extraccion.nivel_prioridad
    ]

    presentes = sum(
        1
        for campo in campos
        if campo is not None and str(campo).strip() != ""
    )

    total = len(campos)

    return presentes / total if total > 0 else 0.0

"""## calculo completitud"""

# ejemplo calculo score completitud

score = score_completitud(extraccion_validada)

print("Score de completitud:", score)

"""#### CONSISTENCIA"""

# Modelo para evaluar consistencia de la extracción

from pydantic import BaseModel

class EvaluacionConsistencia(BaseModel):
    hay_inconsistencias: bool
    observaciones: list[str]

# Prompt para evaluar consistencia de la extracción

prompt_consistencia = f"""
Eres un sistema de evaluación de extracción de documentos clínicos.

Tu tarea es comparar el documento clínico original con los datos extraídos
y determinar si la extracción representa fielmente la información del documento.

NO debes determinar si un diagnóstico médico es verdadero o falso.
NO debes realizar una evaluación médica independiente.

Considera una inconsistencia únicamente cuando exista una diferencia,
contradicción o interpretación incorrecta entre el documento original
y los datos extraídos.

Verifica especialmente:

- identidad y edad del paciente
- médico solicitante
- estudio o examen mencionado
- indicación clínica
- diagnóstico o impresión clínica
- nivel de prioridad
- cualquier otro dato relevante presente en el documento

IMPORTANTE:

- Si un dato no aparece en el documento y fue extraído como null,
  esto NO es una inconsistencia.
- Si un dato está ausente en el documento, NO debes penalizar su ausencia.
- Si el documento expresa un diagnóstico como sospecha, posibilidad o
  diagnóstico presuntivo y la extracción conserva ese mismo nivel de certeza,
  esto ES CONSISTENTE.
- Si el documento expresa una sospecha y la extracción la convierte en un
  diagnóstico confirmado, esto SÍ es una inconsistencia.
- No confundas una característica del documento con un error de extracción.
- No inventes información que no aparezca en el documento.

DATOS EXTRAÍDOS:

{extraccion_validada.model_dump_json()}

Devuelve únicamente un objeto JSON válido.

La estructura debe ser exactamente:

{{
    "hay_inconsistencias": true,
    "observaciones": [
        "Descripción concreta de la inconsistencia encontrada"
    ]
}}

Si no existe ninguna inconsistencia relevante, devuelve:

{{
    "hay_inconsistencias": false,
    "observaciones": []
}}
"""

# Limpia posibles bloques Markdown de una respuesta JSON

def limpiar_json(respuesta):
    respuesta = respuesta.strip()

    if respuesta.startswith("```"):
        primera_linea, *resto = respuesta.split("\n")
        respuesta = "\n".join(resto)

    if respuesta.endswith("```"):
        respuesta = respuesta[:-3]

    return respuesta.strip()

"""### CALCULO CONSISTENCIA

#### CONSISTENCIA
"""

# Ejecución + limpieza JSON + parseo + validación de consistencia

resultado_consistencia = consultar_gemini(
    prompt=prompt_consistencia,
    archivo=archivo_gemini
)

respuesta_limpia = limpiar_json(resultado_consistencia)

datos_consistencia = json.loads(respuesta_limpia)

evaluacion_consistencia = EvaluacionConsistencia.model_validate(
    datos_consistencia
)

print(
    "¿Hay inconsistencias?:",
    evaluacion_consistencia.hay_inconsistencias
)

print(
    "Observaciones:",
    evaluacion_consistencia.observaciones
)

"""#### CALCULO SCORE CONFIANZA"""

# Función para cálculo de confianza
# basada en completitud y consistencia

def calcular_confianza(completitud, hay_inconsistencias):
    consistencia = 0.0 if hay_inconsistencias else 1.0

    confianza = (
        completitud * 0.60
        + consistencia * 0.40
    )

    return confianza

# Cálculo del score de confianza

confianza = calcular_confianza(
    score,
    evaluacion_consistencia.hay_inconsistencias
)

print(f"Confianza final: {confianza:.0%}")

"""## GRAFO DE DECISIÓN"""

from typing import TypedDict

class EstadoMediFlow(TypedDict):
    extraccion_valida: bool
    confianza: float
    hay_inconsistencias: bool
    nivel_prioridad: str
    es_urgente: bool
    ruta: str
    mensaje: str

def detectar_urgencia(estado: EstadoMediFlow):
    es_urgente = estado["nivel_prioridad"] == "Urgente"

    return {
        "es_urgente": es_urgente
    }

# Umbral mínimo de confianza para procesamiento automático

UMBRAL_CONFIANZA = 0.80

print(f"Umbral de confianza: {UMBRAL_CONFIANZA:.0%}")

def enrutar(estado: EstadoMediFlow):

    if not estado["extraccion_valida"]:
        return {"ruta": "auditoria_humana"}

    if estado["es_urgente"]:
        return {"ruta": "emergencia"}

    if estado["hay_inconsistencias"]:
        return {"ruta": "auditoria_humana"}

    if estado["confianza"] < UMBRAL_CONFIANZA:
        return {"ruta": "auditoria_humana"}

    return {"ruta": "caso_estandar"}

"""#### LangGraph"""

!pip install -q langgraph

from langgraph.graph import StateGraph, START, END

# Nodos de salida del enrutamiento

def auditoria_humana(estado: EstadoMediFlow):
    return {
        "mensaje": "Documento enviado a auditoría humana."
    }


def emergencia(estado: EstadoMediFlow):
    return {
        "mensaje": "Documento enviado a la cola de emergencia. Se requiere alerta."
    }


def caso_estandar(estado: EstadoMediFlow):
    return {
        "mensaje": "Documento enviado al procesamiento estándar."
    }

# Nodo de persistencia

def persistencia(estado: EstadoMediFlow):
    return {
        "mensaje": estado["mensaje"] + " Documento listo para persistencia."
    }

# Nodo de notificación

def notificacion(estado: EstadoMediFlow):
    return {
        "mensaje": estado["mensaje"] + " Notificación generada."
    }

# Construcción del grafo de decisión

grafo = StateGraph(EstadoMediFlow)

grafo.add_node("detectar_urgencia", detectar_urgencia)
grafo.add_node("enrutar", enrutar)

grafo.add_node("auditoria_humana", auditoria_humana)
grafo.add_node("emergencia", emergencia)
grafo.add_node("caso_estandar", caso_estandar)

grafo.add_node("persistencia", persistencia)
grafo.add_node("notificacion", notificacion)

grafo.add_edge(START, "detectar_urgencia")
grafo.add_edge("detectar_urgencia", "enrutar")

grafo.add_conditional_edges(
    "enrutar",
    lambda estado: estado["ruta"],
    {
        "auditoria_humana": "auditoria_humana",
        "emergencia": "emergencia",
        "caso_estandar": "caso_estandar"
    }
)

grafo.add_edge("auditoria_humana", "persistencia")
grafo.add_edge("emergencia", "persistencia")
grafo.add_edge("caso_estandar", "persistencia")

grafo.add_edge("persistencia", "notificacion")
grafo.add_edge("notificacion", END)

# Compilar el grafo

app = grafo.compile()

print("Grafo compilado correctamente.")

# Prueba del grafo con un caso urgente y confiable

estado_prueba = {
    "extraccion_valida": True,
    "confianza": 0.89,
    "hay_inconsistencias": False,
    "nivel_prioridad": "Urgente",
    "es_urgente": False,
    "ruta": "",
    "mensaje": ""
}

resultado = app.invoke(estado_prueba)

print(resultado)

# Prueba del grafo con un caso estándar

estado_prueba_estandar = {
    "extraccion_valida": True,
    "confianza": 0.89,
    "hay_inconsistencias": False,
    "nivel_prioridad": "Rutina",
    "es_urgente": False,
    "ruta": "",
    "mensaje": ""
}

resultado_estandar = app.invoke(estado_prueba_estandar)

print(resultado_estandar)

# Prueba del grafo con confianza baja

estado_prueba_auditoria = {
    "extraccion_valida": True,
    "confianza": 0.70,
    "hay_inconsistencias": False,
    "nivel_prioridad": "Rutina",
    "es_urgente": False,
    "ruta": "",
    "mensaje": ""
}

resultado_auditoria = app.invoke(estado_prueba_auditoria)

print(resultado_auditoria)

# Prueba del grafo con extracción inválida

estado_prueba_extraccion_fallida = {
    "extraccion_valida": False,
    "confianza": 0.95,
    "hay_inconsistencias": False,
    "nivel_prioridad": "Rutina",
    "es_urgente": False,
    "ruta": "",
    "mensaje": ""
}

resultado_extraccion_fallida = app.invoke(
    estado_prueba_extraccion_fallida
)

print(resultado_extraccion_fallida)